// Bảng icon Lucide dùng trong app — import tĩnh để bundler tree-shake được.
// DS gốc nạp icon bằng CSS mask từ CDN jsDelivr; ở đây dùng lucide-react để app chạy offline
// và không phụ thuộc CDN. Tên icon giữ nguyên kebab-case như handoff 06 để không phá fidelity.
//
// Thêm icon mới: thêm 1 dòng import + 1 dòng trong ICONS. Đừng dùng `import * as lucide`
// (6095 export, tree-shaking chết, bundle phình).
//
// Bảng này phải phủ CẢ icon do component TDMS tự dùng bên trong (Alert dùng info/triangle-alert,
// StatusPill dùng truck/circle-pause, DataTable dùng ellipsis…) — không chỉ icon app gọi trực tiếp.
// Thiếu icon thì DEV console cảnh báo và ô icon trống, không crash.

import {
  ArrowLeft, Banknote, Building2, Calculator, CalendarClock, CalendarDays, CalendarPlus,
  ChartColumn, Check, ChevronDown, ChevronLeft, ChevronRight, CircleCheck, CirclePause,
  CircleX, ClipboardCheck, ClockAlert, Database, Ellipsis, Eraser, History, Inbox, Info,
  Landmark, Layers, LayoutDashboard, Link, List, LoaderCircle, MapPin, Minus, Package,
  PackageOpen, Pause, Play, Plus, Repeat, RotateCcw, Route, Scale, Search, Send, Settings,
  Settings2, Shield, ShoppingCart, Shuffle, Split, Tags, Trash2, TrendingDown, TrendingUp,
  TriangleAlert, Trophy, Truck, Undo2, Unlink, UserRound, UserRoundCheck, UserRoundPlus,
  UserRoundX, Users, Volleyball, Wallet, WandSparkles, X,
} from 'lucide-react'

export const ICONS = {
  'arrow-left': ArrowLeft,
  banknote: Banknote,
  'building-2': Building2,
  calculator: Calculator,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  'calendar-plus': CalendarPlus,
  'chart-column': ChartColumn,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-check': CircleCheck,
  'circle-pause': CirclePause,
  'circle-x': CircleX,
  'clipboard-check': ClipboardCheck,
  'clock-alert': ClockAlert,
  database: Database,
  ellipsis: Ellipsis,
  eraser: Eraser,
  history: History,
  inbox: Inbox,
  info: Info,
  landmark: Landmark,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  link: Link,
  list: List,
  'loader-circle': LoaderCircle,
  'map-pin': MapPin,
  minus: Minus,
  package: Package,
  'package-open': PackageOpen,
  pause: Pause,
  play: Play,
  plus: Plus,
  repeat: Repeat,
  'rotate-ccw': RotateCcw,
  route: Route,
  scale: Scale,
  search: Search,
  send: Send,
  settings: Settings,
  'settings-2': Settings2,
  shield: Shield,
  'shopping-cart': ShoppingCart,
  shuffle: Shuffle,
  split: Split,
  tags: Tags,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  truck: Truck,
  'undo-2': Undo2,
  unlink: Unlink,
  'user-round': UserRound,
  'user-round-check': UserRoundCheck,
  'user-round-plus': UserRoundPlus,
  'user-round-x': UserRoundX,
  users: Users,
  volleyball: Volleyball,
  wallet: Wallet,
  'wand-sparkles': WandSparkles,
  x: X,
}
