// Bảng icon Lucide dùng trong app — import tĩnh để bundler tree-shake được.
// DS gốc nạp icon bằng CSS mask từ CDN jsDelivr; ở đây dùng lucide-react để app chạy offline
// và không phụ thuộc CDN. Tên icon giữ nguyên kebab-case như handoff 06 để không phá fidelity.
//
// Thêm icon mới: thêm 1 dòng import + 1 dòng trong ICONS. Đừng dùng `import * as lucide`
// (6095 export, tree-shaking chết, bundle phình).
//
// Bảng này phải phủ CẢ icon do component TDMS tự dùng bên trong (Alert dùng info/triangle-alert,
// StatusPill dùng truck/circle-pause, DataTable dùng ellipsis…) — không chỉ icon app gọi trực tiếp.
// Thiếu icon thì DEV console cảnh báo và ô icon trống, không crash.

import {
  Activity, ArrowLeft, ArrowRight, ArrowUpRight, Award, Banknote, Building2, Calculator, Camera, CalendarClock,
  CalendarDays, CalendarPlus, ChevronUp, ChevronsUpDown, CircleAlert, Copy, Crown, Dumbbell, Eye, HandCoins,
  Lock, Medal, Moon, Pencil, Phone, Receipt, Sparkles, Sun, Target, UserRoundCog,
  ChartColumn, Check, ChevronDown, ChevronLeft, ChevronRight, CircleCheck, CirclePause,
  CircleX, ClipboardCheck, ClockAlert, Database, Download, Ellipsis, Eraser, FileSpreadsheet, Flame,
  History, Inbox, Info, Landmark, Layers, LayoutDashboard, LayoutGrid, Link, List, LoaderCircle, MapPin,
  Maximize2, Minus, Package, PackageOpen, Pause, Play, Plus, QrCode, Repeat, RotateCcw,
  Route, Scale, ScanLine, Search,
  Send, Settings, Settings2, Shield, ShoppingCart, Shuffle, Split, Tags, Trash2, TrendingDown,
  TrendingUp, TriangleAlert, Trophy, Truck, Undo2, Unlink, Upload, UserRound, UserRoundCheck,
  UserRoundMinus, UserRoundPlus, UserRoundX, Users, Volleyball, Wallet, WandSparkles, X, Zap,
} from 'lucide-react'

export const ICONS = {
  activity: Activity,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'alert-circle': CircleAlert,
  award: Award,
  banknote: Banknote,
  'building-2': Building2,
  calculator: Calculator,
  camera: Camera,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  'calendar-plus': CalendarPlus,
  'chart-column': ChartColumn,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-up-down': ChevronsUpDown,
  'circle-check': CircleCheck,
  'circle-pause': CirclePause,
  'circle-x': CircleX,
  copy: Copy,
  crown: Crown,
  'clipboard-check': ClipboardCheck,
  'clock-alert': ClockAlert,
  database: Database,
  dumbbell: Dumbbell,
  eye: Eye,
  download: Download,
  ellipsis: Ellipsis,
  eraser: Eraser,
  'file-spreadsheet': FileSpreadsheet,
  flame: Flame,
  'hand-coins': HandCoins,
  history: History,
  inbox: Inbox,
  info: Info,
  landmark: Landmark,
  lock: Lock,
  'maximize-2': Maximize2,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  link: Link,
  list: List,
  'loader-circle': LoaderCircle,
  'map-pin': MapPin,
  medal: Medal,
  minus: Minus,
  moon: Moon,
  package: Package,
  'package-open': PackageOpen,
  pause: Pause,
  pencil: Pencil,
  phone: Phone,
  play: Play,
  plus: Plus,
  'qr-code': QrCode,
  receipt: Receipt,
  repeat: Repeat,
  'rotate-ccw': RotateCcw,
  route: Route,
  scale: Scale,
  'scan-line': ScanLine,
  sparkles: Sparkles,
  search: Search,
  send: Send,
  settings: Settings,
  'settings-2': Settings2,
  shield: Shield,
  'shopping-cart': ShoppingCart,
  shuffle: Shuffle,
  split: Split,
  sun: Sun,
  tags: Tags,
  target: Target,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  truck: Truck,
  'undo-2': Undo2,
  unlink: Unlink,
  upload: Upload,
  'user-round': UserRound,
  'user-round-check': UserRoundCheck,
  'user-round-cog': UserRoundCog,
  'user-round-minus': UserRoundMinus,
  'user-round-plus': UserRoundPlus,
  'user-round-x': UserRoundX,
  users: Users,
  volleyball: Volleyball,
  wallet: Wallet,
  'wand-sparkles': WandSparkles,
  x: X,
  zap: Zap,
}
